name: Feature request
description: Propón una mejora
title: "[feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problema
    attributes:
      label: Problema que resuelve
    validations:
      required: true
  - type: textarea
    id: propuesta
    attributes:
      label: Propuesta
    validations:
      required: true
  - type: textarea
    id: alternativas
    attributes:
      label: Alternativas consideradas
